import { ActionType, IssueType } from './types'

export const ALLOWED_ACTIONS_MAP: Record<IssueType, ActionType[]> = {
  REVENUE_CONTRIBUTION_DIVERGENCE: [
    'REDUCE_DISCOUNT',
    'INCREASE_PRICE',
    'PROMOTE_HIGH_MARGIN_BUNDLE',
  ],
  DISCOUNT_LEAK: [
    'REDUCE_DISCOUNT',
    'INCREASE_PRICE',
    'PROMOTE_HIGH_MARGIN_BUNDLE',
  ],
  PRODUCT_MIX_LEAK: [
    'PROMOTE_HIGH_MARGIN_BUNDLE',
    'REDUCE_LOW_MARGIN_PROMOTION',
  ],
  HIGH_MARGIN_OPPORTUNITY: [
    'PROMOTE_HIGH_MARGIN_BUNDLE',
    'INCREASE_HIGH_MARGIN_PRODUCT_VISIBILITY',
  ],
}
